[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
# white = "#ebdbb2"
white = "#ffffff"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
# white = "#a89984"
white = "#ffffff"
yellow = "#d79921"

[colors.primary]
background = "#161616"
foreground = "#fbf1c7"

[cursor]
style = "Block"
unfocused_hollow = false

[font]
size = 12

[font.normal]
family = "JetBrains Mono SemiBold"

[scrolling]
history = 1000
multiplier = 5

[window]
opacity = 1.0

[window.padding]
x = 14
y = 8
